#!/usr/bin/env python3
"""
gen_entities.py — emit ``mdit-c/src/entities_table.c``.

The HTML5 entity table is sourced from Python's ``html.entities.html5``,
the same table that ``markdown_it.common.entities`` consumes. We strip
trailing ``;`` from each name to match the Python view of the table.

Output format: a sorted (by name, case-sensitive) array of records,
plus a binary-search lookup function. Names live in a pooled byte
buffer so the array entry is a (offset, length) pair instead of a
heap-fragmenting per-entry pointer.

  static const char     k_entity_pool[];     // names + values, contiguous
  static const mdit_entity_record k_entity_table[N];
  bool mdit_entity_lookup(const char *name, size_t len,
                          const char **out, size_t *out_len);

Sorted order is required because the lookup binary-searches.
"""

from __future__ import annotations

import argparse
import html.entities
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "src" / "entities_table.c"


def collect_entities() -> list[tuple[str, str]]:
    seen: dict[str, str] = {}
    for name, chars in html.entities.html5.items():
        canonical = name.rstrip(";")
        # Multiple keys can map to the same canonical name (e.g. ``"amp"``
        # and ``"amp;"``); both should resolve to identical chars in the
        # source dict, but verify just in case.
        if canonical in seen and seen[canonical] != chars:
            raise SystemExit(
                f"entity collision for {canonical!r}: "
                f"{seen[canonical]!r} vs {chars!r}"
            )
        seen[canonical] = chars
    return sorted(seen.items())


def render_c(items: list[tuple[str, str]]) -> str:
    pool = bytearray()
    records: list[tuple[int, int, int, int]] = []  # name_off, name_len, val_off, val_len

    # Strategy: pack each (name, value) into the pool as
    # ``name_bytes || value_utf8_bytes``. Lookups read len bytes; we
    # don't need NUL terminators since records carry explicit lengths.
    for name, chars in items:
        name_bytes = name.encode("ascii")
        value_bytes = chars.encode("utf-8")
        if len(name_bytes) > 255 or len(value_bytes) > 255:
            raise SystemExit(
                f"entity {name!r} or its value exceeds 255 bytes; "
                f"widen the record format"
            )
        name_off = len(pool); pool.extend(name_bytes)
        val_off  = len(pool); pool.extend(value_bytes)
        records.append((name_off, len(name_bytes), val_off, len(value_bytes)))

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_entities.py.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(f" * HTML5 entities: {len(items)}")
    lines.append(f" * Pool bytes:     {len(pool)}")
    lines.append(" */")
    lines.append("")
    lines.append("#include \"entities.h\"")
    lines.append("")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("#include <string.h>")
    lines.append("")
    lines.append("typedef struct mdit_entity_record {")
    lines.append("    uint32_t name_off;")
    lines.append("    uint32_t value_off;")
    lines.append("    uint8_t  name_len;")
    lines.append("    uint8_t  value_len;")
    lines.append("} mdit_entity_record;")
    lines.append("")

    # Emit pool as a hex array. Splitting one byte per emit keeps the
    # diff machine-readable; 16 bytes per line is fine for review.
    lines.append(f"static const uint8_t k_entity_pool[{len(pool)}] = {{")
    chunk = 16
    for i in range(0, len(pool), chunk):
        row = ", ".join(f"0x{b:02X}" for b in pool[i:i + chunk])
        lines.append("    " + row + ",")
    lines.append("};")
    lines.append("")

    lines.append(f"static const mdit_entity_record k_entity_table[{len(records)}] = {{")
    for name_off, name_len, val_off, val_len in records:
        lines.append(
            f"    {{ {name_off:>5}, {val_off:>5}, {name_len:>3}, {val_len:>3} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t k_entity_table_len = {len(records)};")
    lines.append("")

    lines.append(
        "bool mdit_entity_lookup(const char *name, size_t len,\n"
        "                        const char **out, size_t *out_len)"
    )
    lines.append("{")
    lines.append("    if (name == NULL || len == 0) {")
    lines.append("        if (out)     *out = NULL;")
    lines.append("        if (out_len) *out_len = 0;")
    lines.append("        return false;")
    lines.append("    }")
    lines.append("    /* Binary search on the sorted name table. */")
    lines.append("    size_t lo = 0, hi = k_entity_table_len;")
    lines.append("    while (lo < hi) {")
    lines.append("        size_t mid = lo + (hi - lo) / 2;")
    lines.append("        const mdit_entity_record *r = &k_entity_table[mid];")
    lines.append("        size_t n = len < r->name_len ? len : r->name_len;")
    lines.append("        int c = memcmp(name, (const char *)k_entity_pool + r->name_off, n);")
    lines.append("        if (c == 0) {")
    lines.append("            if (len == r->name_len) {")
    lines.append(
        "                if (out)     *out = (const char *)"
        "k_entity_pool + r->value_off;"
    )
    lines.append("                if (out_len) *out_len = r->value_len;")
    lines.append("                return true;")
    lines.append("            }")
    lines.append("            if (len < r->name_len) c = -1; else c = 1;")
    lines.append("        }")
    lines.append("        if (c < 0) hi = mid; else lo = mid + 1;")
    lines.append("    }")
    lines.append("    if (out)     *out = NULL;")
    lines.append("    if (out_len) *out_len = 0;")
    lines.append("    return false;")
    lines.append("}")
    lines.append("")
    lines.append("size_t mdit_entity_count(void)")
    lines.append("{")
    lines.append("    return k_entity_table_len;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"Where to write the generated C file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    items = collect_entities()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_c(items), encoding="utf-8", newline="\n")
    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"({len(items)} entities)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
