#!/usr/bin/env python3
"""
gen_tlds.py — emit ``mdit-c/src/linkifier_tlds_full.c``.

The full ICANN TLD list shipped with linkify-it-py 2.x (~1500 entries).
Upstream linkify-it-py applies this list only when callers opt in via
``Linkify.tlds(TLDS, keep_old=True)``. We mirror that model: the C
linkifier ships a small built-in default list plus 2-char ccTLDs plus
``xn--*`` recognition (matching upstream's *default* behaviour). The
full list compiled by this script is only consulted when the caller
calls :c:func:`mdit_linkifier_default_use_full_tlds(true)`.

The list is exported as:

    bool mdit_linkifier_full_tld_lookup(const char *s, size_t n);

`s`/`n` is treated as ASCII case-insensitive. Names are stored sorted
in a single pooled byte buffer so the per-entry record is just an
``(offset, length)`` pair (no per-entry pointer, fewer relocations).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "src" / "linkifier_tlds_full.c"


def collect_tlds() -> list[str]:
    try:
        from linkify_it.tlds import TLDS
    except ImportError as exc:
        raise SystemExit(
            "linkify-it-py is not installed; run `pip install linkify-it-py`"
        ) from exc

    seen: set[str] = set()
    out: list[str] = []
    for tld in TLDS:
        # Upstream stores lowercase; defensive normalize either way.
        if not isinstance(tld, str) or not tld:
            continue
        norm = tld.lower()
        if norm in seen:
            continue
        seen.add(norm)
        out.append(norm)
    out.sort()
    return out


def render_c(tlds: list[str]) -> str:
    pool = bytearray()
    records: list[tuple[int, int]] = []  # (offset, length)
    for tld in tlds:
        b = tld.encode("ascii")
        if len(b) > 63:
            # ICANN limits each label to 63 octets; defensive guard.
            raise SystemExit(f"TLD {tld!r} exceeds 63 bytes")
        records.append((len(pool), len(b)))
        pool.extend(b)

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_tlds.py.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(f" * Full ICANN TLD list: {len(tlds)} entries")
    lines.append(f" * Pool bytes:          {len(pool)}")
    lines.append(" *")
    lines.append(" * Sourced from linkify-it-py.tlds.TLDS, lowercased and")
    lines.append(" * sorted (ASCII). See `mdit_linkifier_default_use_full_tlds()`.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "linkifier_tlds_full.h"')
    lines.append("")
    lines.append("#include <ctype.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("#include <string.h>")
    lines.append("")
    lines.append("typedef struct mdit_tld_record {")
    lines.append("    uint32_t off;")
    lines.append("    uint8_t  len;")
    lines.append("} mdit_tld_record;")
    lines.append("")

    lines.append(f"static const uint8_t k_tld_pool[{len(pool)}] = {{")
    chunk = 16
    for i in range(0, len(pool), chunk):
        row = ", ".join(f"0x{b:02X}" for b in pool[i : i + chunk])
        lines.append("    " + row + ",")
    lines.append("};")
    lines.append("")

    lines.append(f"static const mdit_tld_record k_tld_table[{len(records)}] = {{")
    for off, n in records:
        lines.append(f"    {{ {off:>6}, {n:>3} }},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t k_tld_table_len = {len(records)};")
    lines.append("")

    lines.append("static int ascii_icmp_n(const char *a, size_t alen,")
    lines.append("                        const char *b, size_t blen)")
    lines.append("{")
    lines.append("    size_t n = (alen < blen) ? alen : blen;")
    lines.append("    for (size_t i = 0; i < n; ++i) {")
    lines.append("        int ca = tolower((unsigned char)a[i]);")
    lines.append("        int cb = tolower((unsigned char)b[i]);")
    lines.append("        if (ca != cb) return ca - cb;")
    lines.append("    }")
    lines.append("    if (alen < blen) return -1;")
    lines.append("    if (alen > blen) return 1;")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    lines.append("bool mdit_linkifier_full_tld_lookup(const char *s, size_t n)")
    lines.append("{")
    lines.append("    if (s == NULL || n == 0 || n > 63) return false;")
    lines.append("    /* Binary search the case-insensitive sorted table. */")
    lines.append("    size_t lo = 0, hi = k_tld_table_len;")
    lines.append("    while (lo < hi) {")
    lines.append("        size_t mid = lo + (hi - lo) / 2;")
    lines.append("        const mdit_tld_record *r = &k_tld_table[mid];")
    lines.append("        const char *t = (const char *)k_tld_pool + r->off;")
    lines.append("        int c = ascii_icmp_n(s, n, t, r->len);")
    lines.append("        if (c == 0) return true;")
    lines.append("        if (c < 0) hi = mid; else lo = mid + 1;")
    lines.append("    }")
    lines.append("    return false;")
    lines.append("}")
    lines.append("")
    lines.append("size_t mdit_linkifier_full_tld_count(void)")
    lines.append("{")
    lines.append("    return k_tld_table_len;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Where to write the generated C file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    tlds = collect_tlds()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_c(tlds), encoding="utf-8", newline="\n")
    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"({len(tlds)} TLDs)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
