#!/usr/bin/env python3
"""
gen_unicode_tables.py — emit ``mdit-c/src/utf_tables.c``.

Produces a 2-level bitmap that answers ``isPunctChar`` (Unicode general
category in {P*, S*}) for every codepoint in [0, 0x110000). The table
is generated from the Python interpreter's bundled ``unicodedata``, so
the C port classifies the *same* UCD version that the Python reference
uses — no drift between the two implementations.

Layout:

    /* For each Unicode plane page (256 codepoints), pack a 256-bit
     * bitmap into 32 bytes. Pages that are entirely zero share a
     * canonical empty page; identical pages are deduplicated. */
    static const uint8_t  k_punct_pages[N_PAGES][32];
    static const uint16_t k_punct_index[0x1100];

    bool mdit_is_punct(uint32_t cp) {
        if (cp >= 0x110000u) return false;
        const uint8_t *page = k_punct_pages[k_punct_index[cp >> 8]];
        return (page[(cp & 0xFF) >> 3] >> (cp & 7)) & 1;
    }

The generator also writes a tiny header comment with:
  - the UCD version it was generated against;
  - the population count of each table (sanity-check against Python).

Re-run any time the Python toolchain ships a new UCD version. CI fails
if the committed file drifts vs the regenerated one.
"""

from __future__ import annotations

import argparse
import sys
import unicodedata
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "src" / "utf_tables.c"

PAGE_BITS = 8
PAGE_SIZE = 1 << PAGE_BITS
NUM_PAGES = 0x110000 // PAGE_SIZE  # 0x1100 == 4352


def is_punct_codepoint(cp: int) -> bool:
    """Mirror ``markdown_it.common.utils.isPunctChar`` semantics.

    Unicode general categories starting with 'P' (punctuation) or 'S'
    (symbols). Surrogates (U+D800..U+DFFF) are always 'Cs' so they
    return False; we still iterate them to keep the bitmap aligned.
    """
    cat = unicodedata.category(chr(cp))
    return cat[:1] in ("P", "S")


def build_pages() -> tuple[list[bytes], list[int]]:
    """Build deduplicated 32-byte pages plus an index per Unicode page.

    Returns (pages, index) where:
      - pages[i] is a 32-byte payload (256 bits, little-endian within byte).
      - index[page_id] is the position of pages used by codepoints
        in [page_id * 256, page_id * 256 + 256).
    """
    pages_unique: OrderedDict[bytes, int] = OrderedDict()
    # Always reserve slot 0 for the all-zero page; that lets the lookup
    # treat ``index == 0`` as a fast "definitely false" response.
    empty = bytes(32)
    pages_unique[empty] = 0

    index: list[int] = [0] * NUM_PAGES
    for page_id in range(NUM_PAGES):
        base = page_id << PAGE_BITS
        bits = bytearray(32)
        for off in range(PAGE_SIZE):
            cp = base + off
            if cp > 0x10FFFF:
                continue
            if is_punct_codepoint(cp):
                bits[off >> 3] |= 1 << (off & 7)
        page = bytes(bits)
        if page in pages_unique:
            index[page_id] = pages_unique[page]
        else:
            pages_unique[page] = len(pages_unique)
            index[page_id] = pages_unique[page]
    return list(pages_unique.keys()), index


def format_page(b: bytes) -> str:
    items = ", ".join(f"0x{x:02X}" for x in b)
    return "{ " + items + " }"


def render_c(pages: list[bytes], index: list[int]) -> str:
    n_pages = len(pages)
    bytes_used = n_pages * 32 + len(index) * 2  # uint16 per page id
    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_unicode_tables.py.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(f" * UCD version (Python unicodedata): {unicodedata.unidata_version}")
    lines.append(f" * Unique pages:    {n_pages}")
    lines.append(f" * Total bytes:     {bytes_used}")
    lines.append(" */")
    lines.append("")
    lines.append("#include \"utf.h\"")
    lines.append("")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Each row is one deduplicated 256-bit page (32 bytes). */")
    lines.append(f"static const uint8_t k_punct_pages[{n_pages}][32] = {{")
    for i, p in enumerate(pages):
        lines.append(f"    /* page {i:>4} */ {format_page(p)},")
    lines.append("};")
    lines.append("")
    lines.append(
        f"/* For each Unicode \"page\" (256 codepoints), the index of"
        f" the canonical bitmap above.\n"
        f" * Codepoints >= 0x110000 cannot occur. */"
    )
    lines.append(f"static const uint16_t k_punct_index[{NUM_PAGES}] = {{")
    items = [f"{idx:>4}" for idx in index]
    rows = []
    for r in range(0, NUM_PAGES, 16):
        rows.append("    " + ", ".join(items[r:r + 16]) + ",")
    lines.extend(rows)
    lines.append("};")
    lines.append("")
    lines.append("bool mdit_is_punct(uint32_t cp)")
    lines.append("{")
    lines.append("    if (cp >= 0x110000u) return false;")
    lines.append("    uint16_t page = k_punct_index[cp >> 8];")
    lines.append("    return ((k_punct_pages[page][(cp & 0xFFu) >> 3] >>"
                  " (cp & 7u)) & 1u) != 0u;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Where to write the generated C file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    pages, index = build_pages()

    # Sanity: independently count punct codepoints two ways.
    via_py = sum(1 for cp in range(0x110000) if is_punct_codepoint(cp))
    via_table = 0
    for page_id in range(NUM_PAGES):
        page = pages[index[page_id]]
        for byte in page:
            via_table += bin(byte).count("1")
        if page_id == NUM_PAGES - 1:
            # Truncate — we rolled past 0x10FFFF when building the last
            # page; any 'extra' bits past the cap should already be 0.
            pass

    if via_py != via_table:
        print(
            f"sanity check failed: python sees {via_py} punct codepoints, "
            f"table has {via_table}",
            file=sys.stderr,
        )
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_c(pages, index), encoding="utf-8", newline="\n")

    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"(UCD {unicodedata.unidata_version}, "
        f"{len(pages)} unique pages, "
        f"{via_table} punct codepoints)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
