#!/usr/bin/env python3
"""
gen_casefold.py — emit ``mdit-c/src/case_fold.c``.

Produces a sorted ``(cp, off, len)`` table plus a flat UTF-8 byte pool
that mirror Python's ``chr(cp).lower().upper()`` for every codepoint
that maps to itself differently after that round-trip.

This is exactly the normalization upstream ``markdown-it-py`` applies
to reference labels (``markdown_it.common.utils.normalizeReference``):
trim, collapse internal whitespace, then ``s.lower().upper()``. The
double pass intentionally exploits the fact that some characters lack
either a lowercase form (``ϴ``, ``Ω``, ``K``, ``Å``, …) or an uppercase
form (``ς`` lowers to itself but only because Final_Sigma already fired
in the *previous* lower pass — but its uppercase is always Σ).

Per-codepoint mapping is sufficient for ``lower().upper()`` even though
``str.lower()`` does apply Final_Sigma context: both σ (U+03C3) and ς
(U+03C2) uppercase to Σ (U+03A3), so the round trip collapses sigma
variants regardless of which lowercase form ``str.lower()`` produced.

Layout (in the generated file)::

    typedef struct {
        uint32_t cp;
        uint16_t off;   // byte offset into k_case_fold_pool
        uint8_t  len;   // 1..6
    } mdit_case_fold_entry;
    static const mdit_case_fold_entry k_case_fold_table[N];
    static const char k_case_fold_pool[P];

    bool mdit_case_fold_lookup(uint32_t cp, const char **out, size_t *len) {
        // binary search k_case_fold_table by cp.
    }

Re-run any time the host Python ships a new UCD version. The header
records ``unicodedata.unidata_version`` for cross-checking.
"""

from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "src" / "case_fold.c"


def collect_mappings() -> list[tuple[int, bytes]]:
    """Walk every codepoint and capture `lower().upper()` results that
    differ from the input. Surrogates (U+D800..U+DFFF) are skipped —
    they cannot represent legal scalar values, and ``chr`` will produce
    them but ``.lower().upper()`` is identity for them anyway.
    """
    out: list[tuple[int, bytes]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        s = chr(cp)
        mapped = s.lower().upper()
        if mapped != s:
            out.append((cp, mapped.encode("utf-8")))
    return out


def render_c(mappings: list[tuple[int, bytes]]) -> str:
    """Emit the C file: pool + table + binary-search lookup."""
    pool: bytearray = bytearray()
    # Reuse identical byte sequences via a small dict, since `lower()`
    # often collapses multiple inputs to the same output (e.g. fullwidth
    # forms, mathematical alphanumerics).
    interned: dict[bytes, int] = {}
    rows: list[tuple[int, int, int]] = []
    for cp, b in mappings:
        if b in interned:
            off = interned[b]
        else:
            off = len(pool)
            interned[b] = off
            pool.extend(b)
        rows.append((cp, off, len(b)))

    if len(pool) > 0xFFFF:
        raise RuntimeError(
            f"case_fold pool grew to {len(pool)} bytes — uint16_t off no "
            "longer fits; widen the entry struct"
        )

    max_blen = max(r[2] for r in rows) if rows else 0

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_casefold.py.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(f" * UCD version (Python unicodedata): {unicodedata.unidata_version}")
    lines.append(f" * Mappings:        {len(rows)}")
    lines.append(f" * Byte pool size:  {len(pool)}")
    lines.append(f" * Max output len:  {max_blen}")
    lines.append(" *")
    lines.append(
        " * Each row maps a single input codepoint to the UTF-8 bytes of"
    )
    lines.append(
        " * Python's ``chr(cp).lower().upper()`` (see the module"
    )
    lines.append(
        " * docstring in scripts/gen_casefold.py for the rationale)."
    )
    lines.append(" */")
    lines.append("")
    lines.append('#include "case_fold.h"')
    lines.append("")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint32_t cp;")
    lines.append("    uint16_t off;")
    lines.append("    uint8_t  len;")
    lines.append("} mdit_case_fold_entry;")
    lines.append("")
    lines.append(f"static const char k_case_fold_pool[{len(pool)}] = {{")
    chunk: list[str] = []
    for i, byte in enumerate(pool):
        chunk.append(f"0x{byte:02X}")
        if (i + 1) % 16 == 0:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const mdit_case_fold_entry k_case_fold_table[{len(rows)}] = {{"
    )
    for cp, off, n in rows:
        lines.append(f"    {{ 0x{cp:06X}u, {off:>5d}u, {n:>2d}u }},")
    lines.append("};")
    lines.append("")
    lines.append(
        "bool mdit_case_fold_lookup(uint32_t cp, const char **out, size_t *len)"
    )
    lines.append("{")
    lines.append(f"    size_t lo = 0, hi = {len(rows)};")
    lines.append("    while (lo < hi) {")
    lines.append("        size_t mid = lo + ((hi - lo) >> 1);")
    lines.append("        uint32_t mcp = k_case_fold_table[mid].cp;")
    lines.append("        if (mcp < cp) lo = mid + 1;")
    lines.append("        else if (mcp > cp) hi = mid;")
    lines.append("        else {")
    lines.append(
        "            *out = k_case_fold_pool + k_case_fold_table[mid].off;"
    )
    lines.append("            *len = k_case_fold_table[mid].len;")
    lines.append("            return true;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return false;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Where to write the generated C file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    mappings = collect_mappings()

    text = render_c(mappings)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8", newline="\n")

    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"(UCD {unicodedata.unidata_version}, "
        f"{len(mappings)} mappings)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
