#!/usr/bin/env python3
"""
gen_utf_test_vectors.py — emit a C header with cross-check fixtures
for ``mdit_is_punct`` and ``mdit_is_whitespace``.

Sampling strategy:

  * Every codepoint in [0x0000, 0x0200) — the dense ASCII / Latin-1
    region used heavily by every Markdown document. We don't compress
    this; the test header carries one bit per codepoint and the C side
    iterates byte-by-byte.

  * Stride sample of 1 in 16 codepoints across the BMP, and 1 in 256
    across the supplementary planes. That's enough to catch any plane
    or page misalignment in the lookup without bloating the header.

The output lives at ``mdit-c/tests/utf_vectors.h`` and is regenerated
by CI alongside the regex inventory and oracle, so any UCD upgrade
forces the table generator and the test fixtures to be refreshed in
the same PR.
"""

from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "tests" / "utf_vectors.h"

# Mirror the Python implementation exactly.
def py_is_punct(cp: int) -> bool:
    return unicodedata.category(chr(cp))[:1] in ("P", "S")

def py_is_whitespace(cp: int) -> bool:
    if 0x09 <= cp <= 0x0D:
        return True
    if cp == 0x20:
        return True
    if cp == 0xA0 or cp == 0x1680:
        return True
    if 0x2000 <= cp <= 0x200A:
        return True
    if cp in (0x202F, 0x205F, 0x3000):
        return True
    return False


def sampled_codepoints() -> list[int]:
    seen: set[int] = set()
    samples: list[int] = []

    # Dense run through Latin-1.
    for cp in range(0, 0x200):
        samples.append(cp)
        seen.add(cp)

    # Stride 16 across the BMP, except for the surrogate range which
    # never represents real codepoints.
    for cp in range(0x200, 0x10000, 16):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if cp not in seen:
            samples.append(cp); seen.add(cp)

    # Stride 256 across the supplementary planes.
    for cp in range(0x10000, 0x110000, 256):
        if cp not in seen:
            samples.append(cp); seen.add(cp)

    # Plus a hand-picked menagerie of edge cases.
    extras = [
        0x0000,                # NUL
        0x007F,                # DEL
        0x00A0,                # NBSP (whitespace)
        0x00AB, 0x00BB,        # « »  (Pi/Pf)
        0x00B6,                # ¶ (Po)
        0x00B9,                # ¹ (No, NOT punct/symbol — should be False)
        0x0030, 0x0039,        # 0..9 (Nd, NOT punct)
        0x0041, 0x007A,        # A..z (L*, NOT punct)
        0x2014,                # — (Pd)
        0x2026,                # … (Po)
        0x20AC,                # € (Sc)
        0x2200,                # ∀ (Sm)
        0x2603,                # ☃ (So)
        0x10FFFF,              # max codepoint
        0x110000,              # invalid (> max)
        0xFFFFFFFF,            # invalid (way out)
    ]
    for cp in extras:
        if cp not in seen:
            samples.append(cp); seen.add(cp)

    samples.sort()
    return samples


def render(samples: list[int]) -> str:
    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_utf_test_vectors.py.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(f" * UCD version (Python unicodedata): {unicodedata.unidata_version}")
    lines.append(f" * Total samples: {len(samples)}")
    lines.append(" */")
    lines.append("#ifndef MDIT_TESTS_UTF_VECTORS_H")
    lines.append("#define MDIT_TESTS_UTF_VECTORS_H")
    lines.append("")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct mdit_utf_vector {")
    lines.append("    uint32_t cp;")
    lines.append("    bool     is_punct;")
    lines.append("    bool     is_whitespace;")
    lines.append("} mdit_utf_vector;")
    lines.append("")
    lines.append(f"static const mdit_utf_vector k_utf_vectors[{len(samples)}] = {{")
    for cp in samples:
        # For invalid codepoints we still emit the expected answers
        # (both False) — the C side asserts the invalid sentinel
        # behaviour.
        if cp < 0x110000:
            ip = py_is_punct(cp)
            iw = py_is_whitespace(cp)
        else:
            ip = False
            iw = False
        lines.append(
            f"    {{ 0x{cp:08X}u, {'true' if ip else 'false'}, "
            f"{'true' if iw else 'false'} }},"
        )
    lines.append("};")
    lines.append(f"static const size_t k_utf_vectors_len = {len(samples)};")
    lines.append("")
    lines.append("#endif /* MDIT_TESTS_UTF_VECTORS_H */")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"Where to write the C header (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    samples = sampled_codepoints()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(samples), encoding="utf-8", newline="\n")
    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"({len(samples)} samples, UCD {unicodedata.unidata_version})."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
