#!/usr/bin/env python3
"""
gen_token_test_vectors.py — emit ``mdit-c/tests/token_vectors.h``.

Builds a handful of representative ``Token`` shapes via the *actual*
Python ``markdown_it.token.Token`` class, runs them through
``json.dumps(token.as_dict(as_upstream=True), ensure_ascii=False)``,
and emits a C header where each vector is a (label, expected_json)
pair. The C test then constructs the same shape with the C ``mdit_token``
API and asserts byte equality.

This is the strongest contract we can write before the parser exists:
any divergence between the C JSON encoder and Python's stable output
fails the build.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "tests" / "token_vectors.h"


def build_cases():
    sys.path.insert(0, str(REPO_ROOT))
    from markdown_it.token import Token

    cases = []

    # 1. Minimal token: no attrs, no map, no children.
    t = Token(type="paragraph_open", tag="p", nesting=1)
    cases.append(("paragraph_open_minimal", t))

    # 2. Attrs (preserving insertion order) + source map.
    t = Token(type="link_open", tag="a", nesting=1)
    t.attrSet("href", "/url")
    t.attrSet("title", "home")
    t.map = [3, 5]
    cases.append(("link_open_with_attrs_and_map", t))

    # 3. Inline code with content + backtick markup.
    t = Token(type="code_inline", tag="code", nesting=0)
    t.content = "x = 1"
    t.markup = "`"
    cases.append(("code_inline_with_content", t))

    # 4. Inline container with empty children list (NOT None).
    t = Token(type="inline", tag="", nesting=0)
    t.children = []
    cases.append(("inline_empty_children", t))

    # 5. Inline container with one text child.
    parent = Token(type="inline", tag="", nesting=0)
    child = Token(type="text", tag="", nesting=0)
    child.content = "hi"
    parent.children = [child]
    cases.append(("inline_with_one_child", parent))

    # 6. UTF-8 content (verifies ensure_ascii=False passthrough).
    t = Token(type="text", tag="", nesting=0)
    t.content = "h\u00e9llo \u20ac"  # héllo €
    cases.append(("text_utf8", t))

    # 7. Control chars in content.
    t = Token(type="text", tag="", nesting=0)
    t.content = "a\nb\tc\rd\\e\"f"
    cases.append(("text_control_and_quotes", t))

    # 8. block + hidden flags toggled.
    t = Token(type="hr", tag="hr", nesting=0)
    t.markup = "---"
    t.block = True
    t.map = [0, 1]
    cases.append(("hr_block", t))

    # 9. Hidden paragraph (tight list).
    t = Token(type="paragraph_open", tag="p", nesting=1)
    t.hidden = True
    t.block = True
    cases.append(("paragraph_open_hidden", t))

    return cases


def render(cases) -> str:
    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_token_test_vectors.py.")
    lines.append(" * DO NOT EDIT BY HAND. */")
    lines.append("#ifndef MDIT_TESTS_TOKEN_VECTORS_H")
    lines.append("#define MDIT_TESTS_TOKEN_VECTORS_H")
    lines.append("")
    lines.append("/* Each case ID below has both a label string and the")
    lines.append(" * expected JSON output for that token. The C test calls")
    lines.append(" * a builder that knows how to construct the matching")
    lines.append(" * mdit_token, then asserts mdit_token_to_json produces")
    lines.append(" * exactly the bytes below. */")
    lines.append("")
    for label, t in cases:
        as_dict = t.as_dict(as_upstream=True)
        as_json = json.dumps(as_dict, ensure_ascii=False)
        # Render as a C string literal: escape \ and " and any byte
        # below 0x20. UTF-8 bytes pass through.
        chunks = []
        for ch in as_json.encode("utf-8"):
            if ch == ord("\\"):
                chunks.append("\\\\")
            elif ch == ord('"'):
                chunks.append('\\"')
            elif ch < 0x20 or ch == 0x7F:
                chunks.append(f"\\x{ch:02x}")
            elif ch >= 0x80:
                chunks.append(f"\\x{ch:02x}")
            else:
                chunks.append(chr(ch))
        body = "".join(chunks)
        lines.append(f"#define MDIT_TOKEN_VECTOR_{label.upper()} \"{body}\"")
    lines.append("")
    lines.append("#endif /* MDIT_TESTS_TOKEN_VECTORS_H */")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"Where to write the C header (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    cases = build_cases()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(cases), encoding="utf-8", newline="\n")
    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"({len(cases)} cases)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
