#!/usr/bin/env python3
"""
gen_entity_test_vectors.py — emit ``mdit-c/tests/entity_vectors.h``.

Cross-check fixtures for ``mdit_entity_lookup``: a sample of known
hits, near-miss strings (off-by-one, prefix, wrong case) plus the
full expected count. The header carries (name, expected utf-8 bytes)
pairs that ``test_entities.c`` walks, so any drift in the generated
table fails the test loudly.
"""

from __future__ import annotations

import argparse
import html.entities
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "mdit-c" / "tests" / "entity_vectors.h"


HIT_SAMPLE = [
    "amp", "AMP",          # both casings exist
    "lt", "LT",
    "gt", "GT",
    "quot", "QUOT",
    "apos",
    "nbsp", "NBSP",
    "copy", "COPY",
    "reg", "REG",
    "trade", "TRADE",
    "Aacute", "aacute",    # ascii Latin-1
    "AElig", "aelig",
    "Eacute", "eacute",
    "ntilde", "Ntilde",
    "alpha", "beta", "gamma",
    "Alpha", "Beta", "Gamma",
    "infin",                # ∞
    "rarr", "larr",         # arrows
    "diams", "spades", "hearts", "clubs",
    "acE",                  # multi-codepoint value
    "bnequiv",              # multi-codepoint value
    "zwj", "zwnj",          # zero-width joiners
    "zopf", "Zscr",         # supplementary plane
]

NEAR_MISS_SAMPLE = [
    "amp;",          # we strip ';' before lookup, so this should miss
    "AmpersandX",    # not an entity
    "ampX",          # almost amp
    "am",            # too short
    "AM",            # too short
    "AAcute",        # almost Aacute (extra capital)
    "",              # empty -> miss
    "lt!extra",      # leading match but longer
    "alphA",         # mixed-case mismatch (entity is 'alpha' or 'Alpha')
]


def render(hits: list[tuple[str, str]],
           misses: list[str]) -> str:
    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by mdit-c/scripts/gen_entity_test_vectors.py.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(f" * Hits:   {len(hits)}")
    lines.append(f" * Misses: {len(misses)}")
    lines.append(" */")
    lines.append("#ifndef MDIT_TESTS_ENTITY_VECTORS_H")
    lines.append("#define MDIT_TESTS_ENTITY_VECTORS_H")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append("typedef struct mdit_entity_hit {")
    lines.append("    const char *name;")
    lines.append("    size_t      name_len;")
    lines.append("    const char *value;")
    lines.append("    size_t      value_len;")
    lines.append("} mdit_entity_hit;")
    lines.append("")

    lines.append(f"static const mdit_entity_hit k_entity_hits[{len(hits)}] = {{")
    for name, value in hits:
        nb = name.encode("ascii")
        vb = value.encode("utf-8")
        n_lit = "".join(f"\\x{b:02X}" for b in nb)
        v_lit = "".join(f"\\x{b:02X}" for b in vb)
        lines.append(
            f'    {{ "{n_lit}", {len(nb)}, "{v_lit}", {len(vb)} }},'
        )
    lines.append("};")
    lines.append(f"static const size_t k_entity_hits_len = {len(hits)};")
    lines.append("")

    lines.append("typedef struct mdit_entity_miss {")
    lines.append("    const char *name;")
    lines.append("    size_t      name_len;")
    lines.append("} mdit_entity_miss;")
    lines.append("")
    lines.append(f"static const mdit_entity_miss k_entity_misses[{len(misses)}] = {{")
    for name in misses:
        nb = name.encode("ascii")
        if nb:
            n_lit = "".join(f"\\x{b:02X}" for b in nb)
        else:
            n_lit = ""
        lines.append(f'    {{ "{n_lit}", {len(nb)} }},')
    lines.append("};")
    lines.append(f"static const size_t k_entity_misses_len = {len(misses)};")
    lines.append("")
    lines.append("#endif /* MDIT_TESTS_ENTITY_VECTORS_H */")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"Where to write the C header (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    table = {
        name.rstrip(";"): chars
        for name, chars in html.entities.html5.items()
    }

    hits: list[tuple[str, str]] = []
    for name in HIT_SAMPLE:
        if name not in table:
            print(
                f"warning: HIT_SAMPLE entry {name!r} not in html5 table; skipping",
                file=sys.stderr,
            )
            continue
        hits.append((name, table[name]))

    misses = [n for n in NEAR_MISS_SAMPLE if n not in table]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(hits, misses), encoding="utf-8", newline="\n")
    print(
        f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()} "
        f"({len(hits)} hits, {len(misses)} misses)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
