r"""Sweep `tests/test_cmark_spec/commonmark.json` and append every case
that exercises *only* the rules the C port has shipped so far, to
`mdit-c/tests/block_oracle.h`.

Filtering rule: skip any case where the input contains characters that
can fire a rule we haven't ported yet. As inline rules are added the
filter is loosened in lockstep -- see `_INLINE_SPECIAL` below for the
current set.

This widens the regression net from ~75 hand-picked cases to several
hundred upstream-curated ones, which is far more likely to catch
subtle off-by-ones in the block driver.
"""
from __future__ import annotations

import json
from pathlib import Path

from markdown_it import MarkdownIt

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "tests" / "test_cmark_spec" / "commonmark.json"
OUT  = ROOT / "mdit-c" / "tests" / "block_oracle.h"


# Inline-special characters that fire rules the C port hasn't ported
# yet. The list shrinks as Phase 3 progresses:
#
#   ported -> filter loosened
#   ----------------------------
#   `text`, `newline`, `escape`, `backticks`, `entity`
#       => `\`, ``, `&` removed below.
#   `table` (block, GFM)
#       => `|` removed below.
#   `emphasis` + `balance_pairs` + `fragments_join`
#       => `*`, `_` removed below.
#   `link`, `image`, `autolink`, `html_inline` (gated on html=False
#       inputs in the spec corpus, which covers the bulk)
#       => `[`, `]`, `!`, `<`, `>` removed below.
#
#   To add later:
#   `linkify`      => `:`, `@`
_INLINE_SPECIAL = set("$@%^{}~?")


def is_block_only(src: str) -> bool:
    """True if `src` doesn't contain any character that would fire an
    inline rule beyond plain text."""
    for ch in src:
        if ch in _INLINE_SPECIAL:
            return False
    return True


def main() -> None:
    cases = json.loads(SPEC.read_text(encoding="utf-8"))

    head_path = ROOT / "mdit-c" / "scripts" / "gen_block_oracle.py"
    import importlib.util
    spec_loader = importlib.util.spec_from_file_location("gen_block_oracle", head_path)
    assert spec_loader and spec_loader.loader
    gen_mod = importlib.util.module_from_spec(spec_loader)
    spec_loader.loader.exec_module(gen_mod)
    hand_cases: list = list(gen_mod.CASES)

    spec_cases: list = []
    seen_inputs = {gen_mod._normalize(c)[1] for c in hand_cases}
    for c in cases:
        src = c["markdown"]
        if not is_block_only(src):
            continue
        if src in seen_inputs:
            continue
        seen_inputs.add(src)
        spec_cases.append((f"spec_{c['example']}", src, {}))

    all_cases = hand_cases + spec_cases

    lines = [
        "/* Auto-generated by scripts/gen_block_oracle.py + sweep_block_oracle.py — do not edit. */",
        "/* Hand-curated cases first, then a filtered slice of the upstream",
        " * CommonMark spec corpus that doesn't exercise inline rules we",
        " * haven't ported yet. Cross-checked against",
        " * markdown_it.MarkdownIt('default', opts).render(). */",
        "#ifndef MDIT_TESTS_BLOCK_ORACLE_H",
        "#define MDIT_TESTS_BLOCK_ORACLE_H",
        "",
        "#define MDIT_BLOCK_ORACLE_OPT_HTML        0x1u",
        "#define MDIT_BLOCK_ORACLE_OPT_LINKIFY     0x2u",
        "#define MDIT_BLOCK_ORACLE_OPT_FULL_TLDS   0x4u",
        "#define MDIT_BLOCK_ORACLE_OPT_TYPOGRAPHER 0x8u",
        "",
        "typedef struct mdit_block_oracle_case {",
        "    const char *title;",
        "    const char *input;",
        "    size_t      input_len;",
        "    const char *html;",
        "    size_t      html_len;",
        "    unsigned    opts;",
        "} mdit_block_oracle_case;",
        "",
        "static const mdit_block_oracle_case MDIT_BLOCK_ORACLE[] = {",
    ]
    for case in all_cases:
        title, src, opts = gen_mod._normalize(case)
        lines.append(gen_mod._emit_row(title, src, opts))
    lines.extend([
        "};",
        "",
        "static const size_t MDIT_BLOCK_ORACLE_LEN =",
        "    sizeof(MDIT_BLOCK_ORACLE) / sizeof(MDIT_BLOCK_ORACLE[0]);",
        "",
        "#endif /* MDIT_TESTS_BLOCK_ORACLE_H */",
        "",
    ])
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} with {len(hand_cases)} hand cases + {len(spec_cases)} spec cases")


if __name__ == "__main__":
    main()
