/* AUTO-GENERATED by mdit-c/scripts/gen_token_test_vectors.py.
 * DO NOT EDIT BY HAND. */
#ifndef MDIT_TESTS_TOKEN_VECTORS_H
#define MDIT_TESTS_TOKEN_VECTORS_H

/* Each case ID below has both a label string and the
 * expected JSON output for that token. The C test calls
 * a builder that knows how to construct the matching
 * mdit_token, then asserts mdit_token_to_json produces
 * exactly the bytes below. */

#define MDIT_TOKEN_VECTOR_PARAGRAPH_OPEN_MINIMAL "{\"type\": \"paragraph_open\", \"tag\": \"p\", \"nesting\": 1, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": null, \"content\": \"\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_LINK_OPEN_WITH_ATTRS_AND_MAP "{\"type\": \"link_open\", \"tag\": \"a\", \"nesting\": 1, \"attrs\": [[\"href\", \"/url\"], [\"title\", \"home\"]], \"map\": [3, 5], \"level\": 0, \"children\": null, \"content\": \"\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_CODE_INLINE_WITH_CONTENT "{\"type\": \"code_inline\", \"tag\": \"code\", \"nesting\": 0, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": null, \"content\": \"x = 1\", \"markup\": \"`\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_INLINE_EMPTY_CHILDREN "{\"type\": \"inline\", \"tag\": \"\", \"nesting\": 0, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": [], \"content\": \"\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_INLINE_WITH_ONE_CHILD "{\"type\": \"inline\", \"tag\": \"\", \"nesting\": 0, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": [{\"type\": \"text\", \"tag\": \"\", \"nesting\": 0, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": null, \"content\": \"hi\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}], \"content\": \"\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_TEXT_UTF8 "{\"type\": \"text\", \"tag\": \"\", \"nesting\": 0, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": null, \"content\": \"h\xc3\xa9llo \xe2\x82\xac\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_TEXT_CONTROL_AND_QUOTES "{\"type\": \"text\", \"tag\": \"\", \"nesting\": 0, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": null, \"content\": \"a\\nb\\tc\\rd\\\\e\\\"f\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": false, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_HR_BLOCK "{\"type\": \"hr\", \"tag\": \"hr\", \"nesting\": 0, \"attrs\": null, \"map\": [0, 1], \"level\": 0, \"children\": null, \"content\": \"\", \"markup\": \"---\", \"info\": \"\", \"meta\": {}, \"block\": true, \"hidden\": false}"
#define MDIT_TOKEN_VECTOR_PARAGRAPH_OPEN_HIDDEN "{\"type\": \"paragraph_open\", \"tag\": \"p\", \"nesting\": 1, \"attrs\": null, \"map\": null, \"level\": 0, \"children\": null, \"content\": \"\", \"markup\": \"\", \"info\": \"\", \"meta\": {}, \"block\": true, \"hidden\": true}"

#endif /* MDIT_TESTS_TOKEN_VECTORS_H */
