/* AUTO-GENERATED by mdit-c/scripts/gen_url_test_vectors.py.
 * DO NOT EDIT BY HAND.
 * mdurl version: 0.1.2
 */
#ifndef MDIT_TESTS_URL_VECTORS_H
#define MDIT_TESTS_URL_VECTORS_H

#include <stdbool.h>
#include <stddef.h>

typedef struct mdit_url_parse_case {
    const char *input;
    size_t      input_len;
    struct {
        bool       present;
        const char *data;
        size_t      len;
    } protocol, auth, port, hostname, search, hash, pathname;
    bool        slashes;
    const char *format;
    size_t      format_len;
} mdit_url_parse_case;

static const mdit_url_parse_case k_url_parse_cases[28] = {
    {
        "", 0,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        false,
        "", 0
    },
    {
        "/", 1,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/", 1 },
        false,
        "/", 1
    },
    {
        "//", 2,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "//", 2 },
        false,
        "//", 2
    },
    {
        "///", 3,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "///", 3 },
        false,
        "///", 3
    },
    {
        "/foo/bar", 8,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/foo/bar", 8 },
        false,
        "/foo/bar", 8
    },
    {
        "./relative", 10,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "./relative", 10 },
        false,
        "./relative", 10
    },
    {
        "?query=1", 8,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "?query=1", 8 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        false,
        "?query=1", 8
    },
    {
        "/path?q=1", 9,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "?q=1", 4 },
        { false, NULL, 0 },
        { true, "/path", 5 },
        false,
        "/path?q=1", 9
    },
    {
        "/path?q=1#frag", 14,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "?q=1", 4 },
        { true, "#frag", 5 },
        { true, "/path", 5 },
        false,
        "/path?q=1#frag", 14
    },
    {
        "http://example.com", 18,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "example.com", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "", 0 },
        true,
        "http://example.com", 18
    },
    {
        "http://example.com/", 19,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "example.com", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/", 1 },
        true,
        "http://example.com/", 19
    },
    {
        "http://example.com/path?q=1#frag", 32,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "example.com", 11 },
        { true, "?q=1", 4 },
        { true, "#frag", 5 },
        { true, "/path", 5 },
        true,
        "http://example.com/path?q=1#frag", 32
    },
    {
        "https://user:pass@example.com:8080/p?q#h", 40,
        { true, "https:", 6 },
        { true, "user:pass", 9 },
        { true, "8080", 4 },
        { true, "example.com", 11 },
        { true, "?q", 2 },
        { true, "#h", 2 },
        { true, "/p", 2 },
        true,
        "https://user:pass@example.com:8080/p?q#h", 40
    },
    {
        "ftp://files.example.com/dir/file.txt", 36,
        { true, "ftp:", 4 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "files.example.com", 17 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/dir/file.txt", 13 },
        true,
        "ftp://files.example.com/dir/file.txt", 36
    },
    {
        "javascript:alert(1)", 19,
        { true, "javascript:", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "alert(1)", 8 },
        false,
        "javascript:alert(1)", 19
    },
    {
        "javascript:void(0)", 18,
        { true, "javascript:", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "void(0)", 7 },
        false,
        "javascript:void(0)", 18
    },
    {
        "//cdn.example.com/script.js", 27,
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "//cdn.example.com/script.js", 27 },
        false,
        "//cdn.example.com/script.js", 27
    },
    {
        "  http://trim-me.test/  ", 24,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "trim-me.test", 12 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/", 1 },
        true,
        "http://trim-me.test/", 20
    },
    {
        "mailto:foo@bar.test", 19,
        { true, "mailto:", 7 },
        { true, "foo", 3 },
        { false, NULL, 0 },
        { true, "bar.test", 8 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        false,
        "mailto:foo@bar.test", 19
    },
    {
        "data:text/plain,hello", 21,
        { true, "data:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "text", 4 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/plain,hello", 12 },
        false,
        "data:text/plain,hello", 21
    },
    {
        "http://[::1]:80/", 16,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { true, "80", 2 },
        { true, "::1", 3 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/", 1 },
        true,
        "http://[::1]:80/", 16
    },
    {
        "http://example.com:80", 21,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { true, "80", 2 },
        { true, "example.com", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "", 0 },
        true,
        "http://example.com:80", 21
    },
    {
        "http://example.com:", 19,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "example.com", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, ":", 1 },
        true,
        "http://example.com:", 19
    },
    {
        "http://x@y@example.com/path@inside", 34,
        { true, "http:", 5 },
        { true, "x@y", 3 },
        { false, NULL, 0 },
        { true, "example.com", 11 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/path@inside", 12 },
        true,
        "http://x@y@example.com/path@inside", 34
    },
    {
        "http://ex\xc3\xa4mple.com/path", 24,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "ex\xc3\xa4mple.com", 12 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/path", 5 },
        true,
        "http://ex\xc3\xa4mple.com/path", 24
    },
    {
        "http://\xd0\xbf\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x80.\xd1\x80\xd1\x84/", 25,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "\xd0\xbf\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x80.\xd1\x80\xd1\x84", 17 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/", 1 },
        true,
        "http://\xd0\xbf\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x80.\xd1\x80\xd1\x84/", 25
    },
    {
        "http://example.com/with space?q=1", 33,
        { true, "http:", 5 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "example.com", 11 },
        { true, "?q=1", 4 },
        { false, NULL, 0 },
        { true, "/with space", 11 },
        true,
        "http://example.com/with space?q=1", 33
    },
    {
        "irc://chat.example.com:6667/channel", 35,
        { true, "irc:", 4 },
        { false, NULL, 0 },
        { true, "6667", 4 },
        { true, "chat.example.com", 16 },
        { false, NULL, 0 },
        { false, NULL, 0 },
        { true, "/channel", 8 },
        true,
        "irc://chat.example.com:6667/channel", 35
    },
};
static const size_t k_url_parse_cases_len = 28;

typedef struct mdit_url_encode_case {
    const char *input;  size_t input_len;
    const char *output; size_t output_len;
} mdit_url_encode_case;

static const mdit_url_encode_case k_url_encode_default_cases[11] = {
    { "", 0, "", 0 },
    { "hello world", 11, "hello%20world", 13 },
    { "https://example.com/path?q=1", 28, "https://example.com/path?q=1", 28 },
    { "h\xc3\xa9llo", 6, "h%C3%A9llo", 10 },
    { "caf\xc3\xa9/\xe2\x82\xac", 9, "caf%C3%A9/%E2%82%AC", 19 },
    { "\xe4\xb8\xad\xe6\x96\x87", 6, "%E4%B8%AD%E6%96%87", 18 },
    { "\xf0\x9f\x98\x80 emoji", 10, "%F0%9F%98%80%20emoji", 20 },
    { "a%20b", 5, "a%20b", 5 },
    { "%XYZ%2g", 7, "%25XYZ%252g", 11 },
    { "100% pure", 9, "100%25%20pure", 13 },
    { "foo[]{}|\\^<>\"'", 14, "foo%5B%5D%7B%7D%7C%5C%5E%3C%3E%22'", 34 },
};
static const size_t k_url_encode_default_cases_len = 11;

static const mdit_url_encode_case k_url_encode_component_cases[2] = {
    { "a/b?c=d&e=f", 11, "a%2Fb%3Fc%3Dd%26e%3Df", 21 },
    { "h\xc3\xa9llo&world", 12, "h%C3%A9llo%26world", 18 },
};
static const size_t k_url_encode_component_cases_len = 2;

static const mdit_url_encode_case k_url_decode_default_cases[14] = {
    { "", 0, "", 0 },
    { "hello", 5, "hello", 5 },
    { "hello%20world", 13, "hello world", 11 },
    { "h%C3%A9llo", 10, "h\xc3\xa9llo", 6 },
    { "caf%C3%A9", 9, "caf\xc3\xa9", 5 },
    { "%E2%82%AC", 9, "\xe2\x82\xac", 3 },
    { "%F0%9F%98%80", 12, "\xf0\x9f\x98\x80", 4 },
    { "a%2fb", 5, "a%2Fb", 5 },
    { "a%2Fb", 5, "a%2Fb", 5 },
    { "a%3Bb", 5, "a%3Bb", 5 },
    { "invalid%XY", 10, "invalid%XY", 10 },
    { "%C3%28", 6, "\xef\xbf\xbd(", 4 },
    { "%E2%82", 6, "\xef\xbf\xbd\xef\xbf\xbd", 6 },
    { "a%20b%E2%82%ACc", 15, "a b\xe2\x82\xac" "c", 7 },
};
static const size_t k_url_decode_default_cases_len = 14;

static const mdit_url_encode_case k_url_decode_component_cases[1] = {
    { "a%2Fb", 5, "a/b", 3 },
};
static const size_t k_url_decode_component_cases_len = 1;

#endif /* MDIT_TESTS_URL_VECTORS_H */
